pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
		sh 'apt-get upgrade && apt-get install python' //if the pod doesn't have python
		sh 'apt-get install docker'
		sh 'pip install selenium webdriver_manager' // for e2e
                sh 'git clone <http..>'
                sh 'cd <project>'
            }
        }
	stage('Build')
	    steps {
                sh 'docker build image .'
            }
	stage('Run')
	    steps {
                sh 'docker run -d -p 8777:5000 image'
            }
    stage('Test')
	    steps {
                
                sh 'python e2e.py && docker-compose push' // && works only if exit code is 0, if issue exit code is 1
            }        
    }
}
