pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                bat 'git clone <http..>'
                bat 'cd <project>'
            }
        }
	stage('Build')
	    steps {
                bat 'docker build image .'
            }
	stage('Run')
	    steps {
                bat 'docker run -d -p 8777:5000 image'
            }
    stage('Test')
	    steps {
                bat 'apt-get upgrade && apt-get install python' //if the pod doesn't have python
                bat 'python e2e.py && docker-compose push'
            }        
    }
}
