version: '3.9'
services:

  WorldOfGames:
    build: ./wog_main_img/.
    image: amitmenashe/wog_main_img
    
  GuessGame:
    build: ./guessgame_img/.
    image: amitmenashe/guessgame_img
   

  MemoryGame:
    build: ./memorygame_img/.
    image: amitmenashe/memorygame_img
    
  CRGame:
    build: ./crgame_img/.
    image: amitmenashe/cr-game_img
    
  DB:
    build: ./wog_mysql_img/.
    image: amitmenashe/wog_mysql_img
    