version: '3.9'
services:

  WorldOfGames:
    image: amitmenashe/wog_main_img
    ports:
      - 80:5000
    environment:
      PYTHONPATH: /guessgame:/memorygame:/crgame
    volumes:
      - guessgame_vol:/guessgame/
      - memorygame_vol:/memorygame/
      - crgame_vol:/crgame/

    depends_on:
      - GuessGame
      - MemoryGame
      - CRGame
     # - DB
  
  GuessGame:
    image: amitmenashe/guessgame_img
    volumes:
      - guessgame_vol:/app

  MemoryGame:
    image: amitmenashe/memorygame_img
    volumes:
      - memorygame_vol:/app

  CRGame:
    image: amitmenashe/cr-game_img
    volumes:
      - crgame_vol:/app
  
  
  # DB:
  #   image: mysql
  #   ports:
  #     - 3306:3306
  #   env_file:
  #    - db.env
  #   volumes:
  #     - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

volumes:
  guessgame_vol:
  memorygame_vol:
  crgame_vol:
