apiVersion: v1
kind: Pod
metadata:
  name: crgame
  namespace: wog
spec:
  containers:
  - name: crgame-container
    image: amitmenashe/crgame_img
    volumeMounts:
    - name: crgame-vol
      mountPath: /app
  volumes:
  - name: crgame-vol
    persistentVolumeClaim:
      claimName: crgame-pvc
