apiVersion: v1
kind: Pod
metadata:
  name: memorygame
  namespace: wog
spec:
  containers:
  - name: memorygame-container
    image: amitmenashe/memorygame_img
    volumeMounts:
    - name: memorygame-vol
      mountPath: /app
  volumes:
  - name: memorygame-vol
    persistentVolumeClaim:
      claimName: memorygame-pvc